Django_Project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import Top

urlpatterns = [
    path('', Top.as_view(), name='top'),
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('login/', include('django.contrib.auth.urls')),
    path('real/', include('real.urls')),
]

Django_Project/login/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'login'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_confirm', TemplateView.as_view(template_name='registration/delete_confirm.html'), name='delete-confirmation'),
    path('delete_complete', views.DeleteView.as_view(), name='delete-complete'),
]

Django_Project/real/urls.py
from django.urls import path
from . import views
from .views import TWU

app_name = 'real'

urlpatterns = [
    path('', TWU.as_view(), name='index'),
]

Django_Project/login/models.py
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone


class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs) 

Django_Project/real/models.py
from django.db import models

class Log(models.Model):
   enter = models.CharField(max_length=150)

   def __str__(self):
       return self.enter

class TweetData(models.Model):
   screenname = models.CharField(max_length=150)
   tweetid = models.IntegerField()
   postdate = models.DateTimeField()
   body = models.TextField()
   rt = models.IntegerField()
   likes = models.IntegerField()
   url = models.URLField()

   def __str__(self):
       return self.screenname

Django_Project/login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

Django_Project/real/forms.py
from django import forms

from .models import Log

class LogForm(forms.ModelForm):
   class Meta:
       model = Log
       fields = ('enter',)

Django_Project/login/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import (
     get_user_model, logout as auth_logout,
)
from .forms import UserCreateForm

User = get_user_model()


class Top(generic.TemplateView):
    template_name = 'top.html'


class SignUpView(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class ProfileView(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        return render(self.request,'registration/profile.html')


class DeleteView(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        user = User.objects.get(email=self.request.user.email)
        user.is_active = False
        user.save()
        auth_logout(self.request)
        return render(self.request,'registration/delete_complete.html')

Django_Project/real/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from .models import TweetData
from .forms import LogForm
from .tw import Tweet #追記部分

class TWU(View):
    def post(self, request):
        data = {"forms": LogForm,
               "TL":TweetData.objects.all()}
        form = LogForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.save()
        #ユーザー名
        u = post.enter

        #タイムラインを5件取得
        tl = Tweet(5)

        tld = tl.get_timeline(u)

        #データベースに登録をする

        for i in tld:
            TweetData.objects.create(screenname=i["screenname"], tweetid=i["ツイートID"], postdate=i["投稿日時"],
                                     body=i["text"], rt=i["RT数"], likes=i["いいね数"], url = i["url"])

        return render(request, 'real/index.html', data)
   

    def get(self, request):
        data = {"forms": LogForm,
                "TL": TweetData.objects.all()}

        return render(request,'real/index.html', data)

Django_Project/login/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static "css/custom.css" %}" rel="stylesheet" />
    <title>django-account</title>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'top' %}">django-account</a></h5>

    <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
        <a class="btn btn-outline-primary btn-sm mr-2" href="{% url 'real:index' %}">Twitter</a>
        <a class="btn btn-outline-primary btn-sm mr-2" href="{% url 'login:profile' %}">マイページ</a>
    {% else %}
        <a class="btn btn-outline-primary btn-sm mr-2" href="{% url 'login' %}">ログイン</a>
        <a class="btn btn-outline-primary btn-sm" href="{% url 'login:signup' %}">入会</a>
    {% endif %}
    </nav>
</div>

<div class="container mt-3">
    {% block body %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
</body>
</html>

Django_Project/login/templates/base_centered.html
{% extends "base.html" %}

{% block body %}
    
    <div class="row text-center">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">

                    {% block content %}{% endblock %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

Django_Project/login/templates/top.html
{% extends "base.html" %}

{% block body %}

    <p>トップページ</p>

{% endblock %}

Django_Project/real/templates/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>System is Normal operation!</h1>

</body>

</html>

Django_Project/real/templates/real/base.html
{% load static %}

<html lang="ja">
<head>
   <meta charset="UTF-8">
   <title>ツイッター</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <script src="https://code.jquery.com/jquery-3.5.0.js" integrity="sha256-r/AaFHrszJtwpe+tHyNi/XCfMxYpbsRg2Uqn0x3s2zc=" crossorigin="anonymous"></script>
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
   <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>

<body>
<header>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
 <a class="navbar-brand" href="#">ツイッター</a>
 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
 </button>
 <div class="collapse navbar-collapse" id="navbarText">
   <ul class="navbar-nav mr-auto">
     <li class="nav-item active">
       <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">サービス</a>
     </li>
     <li class="nav-item">
       <a class="nav-link" href="#">お問い合わせ</a>
     </li>
   </ul>

 </div>
</nav>

</header>
{% block content %}

{% endblock %}


</body>
</html>

Django_Project/real/templates/real/index.html
{% extends 'real/base.html' %}

{% block content %}

<form method="POST" id="form">
	{% csrf_token %}
	{{ forms.as_p }}
	<button type="submit" id="save" class="btn btn-primary">Save</button>
</form>

{% for i in TL %}

<p>{{i.screenname}}</p>
<p>{{i.tweetid}}</p>
<p>{{i.postdate|date:"Y-n-j h:i:s"}}</p>
<p>{{i.body}}</p>
<p>{{i.rt}}</p>
<p>{{i.likes}}</p>
<p>{{i.url}}</p>
{% endfor %}

{% endblock %}